version: 2.1

jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm ci
      # - run: npm ls
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm run lint
      - run: CYPRESS_BASE_URL=https://stayathomebanner-git-${CIRCLE_BRANCH}.masone.now.sh npx cypress run
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

workflows:
  version: 2
  test:
    jobs:
      - test

