# This is a basic workflow to help you get started with Actions

name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: https://stayathomebanner-git-${GITHUB_REF##*/}.masone.now.sh
        with:
          headless: true

